### ISSUE TITLE
cp ../honor/makefile problem

### ISSUE THREAD

**Issue by imFaa** [MiCode/patchrom#103]
`cp: missing destination file operand after '../honor/makefile'
Try 'cp --help' for more information.`

**Comment by linhphi9x94** [comment]
https://github.com/linhphi9x94/Miui8_patchrom_Pantech_IM-A910/blob/master/makefile You can use it

**Comment by imFaa** [comment]
So I have to makefile right?
But where in in patchrom folder or device folder or in OUT folder?
