### ISSUE TITLE
issue with android.policy.jar

### ISSUE THREAD

**Issue by jcorrea86** [MiCode/patchrom#12]
When ever I try to to use "make fullota"  I get the below error.

/home/jr/tools/apktool --quiet d -f /home/jr/miui/system/framework/android.policy.jar out/android.policy_miui

> > > build out/android.policy.jar...
> > > /home/jr/tools/add_miui_smail.sh >/dev/null out/android.policy_miui out/android.policy
> > > /home/jr/tools/apktool --quiet b out/android.policy out/android.policy.jar
> > > Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: java.io.FileInputStream@19e06de8
> > >     at brut.androlib.src.DexFileBuilder.addSmaliFile(DexFileBuilder.java:45)
> > >     at brut.androlib.src.DexFileBuilder.addSmaliFile(DexFileBuilder.java:33)
> > >     at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:64)
> > >     at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:48)
> > >     at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:35)
> > >     at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:222)
> > >     at brut.androlib.Androlib.buildSources(Androlib.java:179)
> > >     at brut.androlib.Androlib.build(Androlib.java:170)
> > >     at brut.androlib.Androlib.build(Androlib.java:154)
> > >     at brut.apktool.Main.cmdBuild(Main.java:182)
> > >     at brut.apktool.Main.main(Main.java:67)
> > > make: **\* [out/android.policy.jar] Error 1

Can't seem to figure this out.

**Comment by iBotPeaches** [comment]
That means your smali is busted.

I'd run "smali android.policy.jar.out", it will tell you where the error is. Go fix it, then apktool will build.

**Comment by jcorrea86** [comment]
well it gave me the reject file when running "make firstpatch" and it only found one smali but it doesn't match at all the actual smali.  For example, the reject file gives me this:

---

**\* 42,48 ****

  # virtual methods
  .method public run()V
!     .locals 5

```
  .prologue
  const/4 v4, 0x0
```

--- 42,48 ----

  # virtual methods
  .method public run()V
!     .locals 6

```
  .prologue
  const/4 v4, 0x0
```

But the actual smali shows this

# virtual methods

.method public onShown(Landroid/os/IBinder;)V
    .locals 3
    .parameter "windowToken"

```
.prologue
.line 3213
if-eqz p1, :cond_0
```

It does not have the .locals line and even the .method public line is completely different so I'm not sure how to proceed with this.

**Comment by iBotPeaches** [comment]
Thats why its in the reject folder...

It couldn't be found. You must look around that file for something similar then that. If its like a $## file, it might even be in a different number.

**Comment by jcorrea86** [comment]
Ok, well then do i make the changes in the temp new-smali or in the original smali that is in the android.policy.jar.out

**Comment by iBotPeaches** [comment]
Neither. Don't touch anything in that /temp folder. Touch the files in the root of your device.

**Comment by jcorrea86** [comment]
Ok I've made the changes that I had to make according to the reject folder. But I am still getting the same error. Is it because I'm using 4.0.4 as my base?

**Comment by iBotPeaches** [comment]
It has nothing to do with base. The smali is wrong. Install smali/baksmali by JF and add them into your PATH like you did with apktool.

So run smali android.policy.jar.out from the ROOT of your device folder
EX:

`source build/envsetup.sh
cd dhd
smali android.policy.jar.out`
If that commands runs without error, then there is a problem.

**Comment by jcorrea86** [comment]
Thank you so much!!!  that worked... the issues listed when running the commands were completely different than the ones listed in the reject folder.
