### ISSUE TITLE
Stuck at Mi boot logo

### ISSUE THREAD

**Issue by DRohan007** [MiCode/patchrom#124]
SIR,
When i had sucessfully builded miui v8 patch rom & fixed all rejects but rom is stucks on Miboot logo i don't know how to take while booting please help me

**Comment by JustRlx93** [comment]
try to get log with ADB service, and then will see what is exactly wrong there

**Comment by DRohan007** [comment]
but how

**Comment by JustRlx93** [comment]
ask google how to get logcat with android debug bridge (ADB) then learn it and try in practice

**Comment by DRohan007** [comment]
iam able to take logcat when the phones is booted but unable to take it when booting

**Comment by JustRlx93** [comment]
http://4pda.ru/forum/index.php?showtopic=715583&view=findpost&p=50835238
translate and try this

**Comment by DRohan007** [comment]
In logcat getting this error
-01 17:44:01.684   323   375 E slim_daemon: [NDK] bindNDKSensors: Sensor server is unavailable.
01-01 17:44:02.052  3772  3772 I ServiceManager: Waiting for service media.camera.proxy...
01-01 17:44:02.164  3771  3771 E Netd    : netlink response contains error (File exists)
01-01 17:44:02.164  3771  3771 E Netd    : Can't add IPv4 default route to dummy0: File exists
01-01 17:44:02.167  3771  3771 D MDnsDS  : MDnsSdListener::Hander starting up
01-01 17:44:02.169  3771  4098 D MDnsDS  : MDnsSdListener starting to monitor
01-01 17:44:02.169  3771  4098 D MDnsDS  : Going to poll with pollCount 1
