### ISSUE TITLE
adding overlays and signing

### ISSUE THREAD

**Issue by 1982Strand** [MiCode/patchrom#13]
I got 2 issues - adding overlays and signing the apks
I'm using ubuntu 11.10 and working on 4.0.4 base.

1st Issue:

> > > build out/framework-res.apk...
> > > add miui overlay resources
> > > /media/DATA/patchrom/tools/remove_redef.py >/dev/null out/framework-res
> > > /media/DATA/patchrom/tools/apktool --quiet b out/framework-res out/framework-res.apk
> > > /media/DATA/patchrom/tools/apktool --quiet if out/framework-res.apk
> > > <<< build out/framework-res.apk completed!
> > > build out/framework-miui-res.apk...
> > > /media/DATA/patchrom/tools/apktool --quiet d -f /media/DATA/patchrom/miui/system/framework/framework-miui-res.apk out/framework-miui-res
> > > ls: cannot access overlay/framework-miui-res/res/[^v]_: No such file or directory
> > > ls: cannot access overlay/framework-miui-res/res/values_: No such file or directory
> > > /media/DATA/patchrom/tools/apktool --quiet b out/framework-miui-res out/framework-miui-res.apk
> > > <<< build out/framework-miui-res.apk completed!

2nd issue:

> > > remove all unnecessary apks from original ZIP file...
> > > <<< remove done!
> > > /media/DATA/patchrom/tools/sign.sh >/dev/null sign.zip out/ZIP
> > > /media/DATA/patchrom/tools/sign.sh: line 47: zipalign: command not found
> > > mv: cannot execute stat() on 'out/ZIP/system/app/Exchange.apk.signed.aligned': No such file or directory
> > > /media/DATA/patchrom/tools/sign.sh: line 47: zipalign: command not found
> > > mv: cannot execute stat() on 'out/ZIP/system/app/MediaProvider.apk.signed.aligned': No such file or directory
> > > /media/DATA/patchrom/tools/sign.sh: line 47: zipalign: command not found
> > > ... And then a lot more of these..

What am i missing?

**Comment by MiuiAnderson** [comment]
The first issue is OK, it is not an error.

And the second issue is because zipalign command can't find.

please ensure you add android-sdk/tools, android-sdk/platform-tools into your PATH

---

发件人: 1982Strand [reply@reply.github.com]
发送时间: 2012年4月24日 6:24
到: 汪文俊
主题: [patchrom] adding overlays and signing (#13)

I got 2 issues - adding overlays and signing the apks
I'm using ubuntu 11.10 and working on 4.0.4 base.

1st Issue:

> > > build out/framework-res.apk...
> > > add miui overlay resources
> > > /media/DATA/patchrom/tools/remove_redef.py >/dev/null out/framework-res
> > > /media/DATA/patchrom/tools/apktool --quiet b out/framework-res out/framework-res.apk
> > > /media/DATA/patchrom/tools/apktool --quiet if out/framework-res.apk
> > > <<< build out/framework-res.apk completed!
> > > build out/framework-miui-res.apk...
> > > /media/DATA/patchrom/tools/apktool --quiet d -f /media/DATA/patchrom/miui/system/framework/framework-miui-res.apk out/framework-miui-res
> > > ls: cannot access overlay/framework-miui-res/res/[^v]_: No such file or directory
> > > ls: cannot access overlay/framework-miui-res/res/values_: No such file or directory
> > > /media/DATA/patchrom/tools/apktool --quiet b out/framework-miui-res out/framework-miui-res.apk
> > > <<< build out/framework-miui-res.apk completed!

2nd issue:

> > > remove all unnecessary apks from original ZIP file...
> > > <<< remove done!
> > > /media/DATA/patchrom/tools/sign.sh >/dev/null sign.zip out/ZIP
> > > /media/DATA/patchrom/tools/sign.sh: line 47: zipalign: command not found
> > > mv: cannot execute stat() on 'out/ZIP/system/app/Exchange.apk.signed.aligned': No such file or directory
> > > /media/DATA/patchrom/tools/sign.sh: line 47: zipalign: command not found
> > > mv: cannot execute stat() on 'out/ZIP/system/app/MediaProvider.apk.signed.aligned': No such file or directory
> > > /media/DATA/patchrom/tools/sign.sh: line 47: zipalign: command not found
> > > ... And then a lot more of these..

What am i missing?

---

Reply to this email directly or view it on GitHub:
https://github.com/MiCode/patchrom/issues/13

**Comment by 1982Strand** [comment]
1st issue:
Ok, so that means there are no overlays for framework-miui-res to be copied? But why does it try to copy the files then??

2nd issue:
Don't understand... My android sdk is located in home/dan/Android/sdk/, this is the contents of my .bashrc file:

# Android tools

export PATH=$PATH/home/dan/Android/sdk/tools:/home/dan/Android/sdk/platform-tools

# Java

export PATH=${PATH}:~/Programmer/Java
PATH=/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/home/dan/Programmer/jdk:/home/dan/bin:/home/dan/Programmer/jdk1.6.0_31:/home/dan/Programmer/jdk/bin:/home/dan/bin:/home/dan/Programmer/jdk1.6.0_31/bin

If i simply type "zipalign" anywhere in terminal, it shows me the options on how to use it, so it must be in the correct PATH, right?

This is what i get when i type "which zipalign": /home/dan/bin/zipalign, don't know if it matters.. The file there is identical to the one in the sdk directory..

**Comment by 1982Strand** [comment]
Found solution.

For some reason, typing "su" before working with patchrom cleared my PATH entries. I have to type "sudo su -p", to keep the PATH, now the signing/zipaligning works fine :)
