### ISSUE TITLE
Issue with make fullota/zipfile

### ISSUE THREAD

**Issue by TheBlueFlame121** [MiCode/patchrom#132]
I am current running Linux mint, serena, cinnamon. I am trying to make miui 8 for samsung galaxy s5 (exynos). It is a really under-developed device. This is a touchwiz device, but I am using an aosp rom by another dev (I have his permission to use it) as base for Miui. I have made firstpatch, fixed rejects, make secondpatch and fixed rejects again. Now when I try to make the final zip, I get the following error

/home/pranshu/bin/patchrom/build/util.mk:157: warning: overriding recipe for target 'stockrom.zip'
/home/pranshu/bin/patchrom/build/porting.mk:204: warning: ignoring old recipe for target 'stockrom.zip'
To add prebuilt files
cp: cannot stat 'stockrom/system/bin/app_process64': No such file or directory
/home/pranshu/bin/patchrom/build/prebuilt.mk:6: recipe for target 'add-prebuilt-files' failed
make: [add-prebuilt-files] Error 1 (ignored)
mv: cannot stat 'out/ZIP/system/bin/app_process64_miui': No such file or directory
/home/pranshu/bin/patchrom/build/prebuilt.mk:6: recipe for target 'add-prebuilt-files' failed
make: [add-prebuilt-files] Error 1 (ignored)
cp: cannot stat 'stockrom/system/bin/app_process32': No such file or directory
/home/pranshu/bin/patchrom/build/prebuilt.mk:6: recipe for target 'add-prebuilt-files' failed
make: [add-prebuilt-files] Error 1 (ignored)
To add preintall files
Add miui prebuilt completed!
>>> Install vendor resources for apktool...
unzip >/dev/null stockrom.zip "system/framework/*.apk" -d out
caution: filename not matched:  system/framework/*.apk
/home/pranshu/bin/patchrom/build/porting.mk:231: recipe for target 'out/apktool/1.apk' failed
make: *** [out/apktool/1.apk] Error 11

Also, I thought i should mention this but I didnt use command to pull files from phone. Instead, I manually decompiled the required files (the jars and framework-res.apk)

I have both java 7 and 8 openjdk installed.
I also have tried the command 'sudo apt-get install lib32stdc++6 lib32z1'.

**Comment by WarrenLobo** [comment]
install andriod sdk tools

**Comment by TheBlueFlame121** [comment]
installed already

**Comment by TheBlueFlame121** [comment]
sdk tools R25.2.5

**Comment by WarrenLobo** [comment]
add these lines in bash.rc
https://docs.google.com/document/d/1K4y9YE_KMWuV8thyaCUrXM_LpFFJEKXGz7LGUbSFsFo/edit

**Comment by TheBlueFlame121** [comment]
why are they crossed out?

**Comment by WarrenLobo** [comment]
i dont know

**Comment by TheBlueFlame121** [comment]
um, they were already there

**Comment by TheBlueFlame121** [comment]
I have followed the video guide by androidFaa

**Comment by WarrenLobo** [comment]
i think there is no stockrom.zip

**Comment by TheBlueFlame121** [comment]
Stockrom.zip is there

**Comment by TheBlueFlame121** [comment]
I don't think I have missed any basic step, I just didn't use make workspace because it gives same error

**Comment by WarrenLobo** [comment]
pull the stock rom from adb and start from beginning

**Comment by TheBlueFlame121** [comment]
That command doesn't work

**Comment by TheBlueFlame121** [comment]
It says that no device/emulator found. Adb reboot recovery works, but once in recovery I can't pull any file. That is why manually decompiled the jars. After that, make workspace doesn't work, same error

**Comment by WarrenLobo** [comment]
update your twrp

**Comment by TheBlueFlame121** [comment]
Is 3.1.0 OK?

**Comment by TheBlueFlame121** [comment]
Mate, please help. @warrenlobo I have installed latest twrp 3.1.1-0 official for my device. my pc can detect that my device is connected but when i use the command, it shows no device. please help

**Comment by TheBlueFlame121** [comment]
I cant get adb to detect my device in recovery, nor can i find the solution to my problem anywhere else. If no other solution turn up, this is the end of the line for my miui

**Comment by TheBlueFlame121** [comment]
I renamed out/apktool/1-miui.apk to 1.apk and worksapce was made. so I ran fullota and got this

pranshu@pranshu-System-Product-Name ~/bin/patchrom $ . build/envsetup.sh
PATCHROM_BRANCH  = marshmallow
ANDROID_PLATFORM = 23
PORT_ROOT        = /home/pranshu/bin/patchrom
ANDROID_TOP      = 
ANDROID_OUT      = 
PORT_PRODUCT     = Unknown
USE_ANDROID_OUT  = 
ANDROID_BRANCH   = 
HOST_OS          = linux
pranshu@pranshu-System-Product-Name ~/bin/patchrom $ cd device
pranshu@pranshu-System-Product-Name ~/bin/patchrom/device $ make workspace
/home/pranshu/bin/patchrom/build/util.mk:157: warning: overriding recipe for target 'stockrom.zip'
/home/pranshu/bin/patchrom/build/porting.mk:204: warning: ignoring old recipe for target 'stockrom.zip'
Prepare workspace completed!
pranshu@pranshu-System-Product-Name ~/bin/patchrom/device $ make fullota
To add prebuilt files
cp: cannot stat 'stockrom/system/bin/app_process64': No such file or directory
/home/pranshu/bin/patchrom/build/prebuilt.mk:6: recipe for target 'add-prebuilt-files' failed
make: [add-prebuilt-files] Error 1 (ignored)
mv: cannot stat 'out/ZIP/system/bin/app_process64_miui': No such file or directory
/home/pranshu/bin/patchrom/build/prebuilt.mk:6: recipe for target 'add-prebuilt-files' failed
make: [add-prebuilt-files] Error 1 (ignored)
cp: cannot stat 'stockrom/system/bin/app_process32': No such file or directory
/home/pranshu/bin/patchrom/build/prebuilt.mk:6: recipe for target 'add-prebuilt-files' failed
make: [add-prebuilt-files] Error 1 (ignored)
To add preintall files
Add miui prebuilt completed!
>>> Install framework resources for apktool...
/home/pranshu/bin/patchrom/tools/apktool --quiet if -p out/apktool /home/pranshu/bin/patchrom/miui/system/framework-res/XXHDPI/framework-res.apk -t miui
install /home/pranshu/bin/patchrom/miui/system/app/XXHDPI/miui/miui.apk
install /home/pranshu/bin/patchrom/miui/system/framework-res/XXHDPI/framework-ext-res/framework-ext-res.apk
install /home/pranshu/bin/patchrom/miui/system/app/XXHDPI/miuisystem/miuisystem.apk
/home/pranshu/bin/patchrom/tools/apktool --quiet d -p out/apktool -t miui -f /home/pranshu/bin/patchrom/miui/system/priv-app/XXHDPI/TeleService/TeleService.apk -o out/TeleService
/home/pranshu/bin/patchrom/tools/patch_miui_app.sh >/dev/null TeleService out/TeleService
>>> build out/TeleService.apk...
/home/pranshu/bin/patchrom/tools/apktool --quiet b -p out/apktool -a /home/pranshu/bin/patchrom/tools/linux-x86/aapt out/TeleService -o out/TeleService.apk
9Patch png fix out/TeleService.apk...
/home/pranshu/bin/patchrom/tools/fix_9patch_png.sh >/dev/null TeleService /home/pranshu/bin/patchrom/miui/system/priv-app/XXHDPI/TeleService/ out TeleService/res
sign platform key for out/TeleService.apk...
<<< build out/TeleService.apk completed!
Copy: out/TeleService.apk to out/ZIP/system/priv-app/TeleService/TeleService.apk
/home/pranshu/bin/patchrom/tools/apktool --quiet d -p out/apktool -t miui -f /home/pranshu/bin/patchrom/miui/system/priv-app/XXHDPI/InCallUI/InCallUI.apk -o out/InCallUI
/home/pranshu/bin/patchrom/tools/patch_miui_app.sh >/dev/null InCallUI out/InCallUI
>>> build out/InCallUI.apk...
/home/pranshu/bin/patchrom/tools/apktool --quiet b -p out/apktool -a /home/pranshu/bin/patchrom/tools/linux-x86/aapt out/InCallUI -o out/InCallUI.apk
9Patch png fix out/InCallUI.apk...
/home/pranshu/bin/patchrom/tools/fix_9patch_png.sh >/dev/null InCallUI /home/pranshu/bin/patchrom/miui/system/priv-app/XXHDPI/InCallUI/ out InCallUI/res
sign shared key for out/InCallUI.apk...
<<< build out/InCallUI.apk completed!
Copy: out/InCallUI.apk to out/ZIP/system/priv-app/InCallUI/InCallUI.apk
make: *** No rule to make target 'stockrom/system/framework/framework-res.apk', needed by 'out/framework-res.apk'.  Stop.

**Comment by TheBlueFlame121** [comment]
@warrenlobo pls

**Comment by superac11** [comment]
That error is due to error on your make file add these 4 lines on the end of your make file.

rm -rf $(ZIP_DIR)/system/bin/app_process32_vendor
	cp -rf stockrom/system/bin/app_process32 $(ZIP_DIR)/system/bin/app_process32
	
	rm -rf $(ZIP_DIR)/system/bin/app_process64_vendor
	cp -rf stockrom/system/bin/app_process32 $(ZIP_DIR)/system/bin/app_process64

And for the 1.apk not found, did you install java ?

**Comment by eternal-will** [comment]
`To add prebuilt files
cp: cannot stat 'stockrom/system/bin/app_process64': No such file or directory
/home/eternal-will/patchrom/build/prebuilt.mk:6: recipe for target 'add-prebuilt-files' failed
make: [add-prebuilt-files] Error 1 (ignored)
mv: cannot stat 'out/ZIP/system/bin/app_process64_miui': No such file or directory
/home/eternal-will/patchrom/build/prebuilt.mk:6: recipe for target 'add-prebuilt-files' failed
make: [add-prebuilt-files] Error 1 (ignored)
cp: cannot stat 'stockrom/system/bin/app_process32': No such file or directory
/home/eternal-will/patchrom/build/prebuilt.mk:6: recipe for target 'add-prebuilt-files' failed
make: [add-prebuilt-files] Error 1 (ignored)
To add preintall files
Add miui prebuilt completed!
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/StepsProvider/StepsProvider.apk to out/ZIP/system/app/StepsProvider/StepsProvider.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/KingSoftCleaner/KingSoftCleaner.apk to out/ZIP/system/app/KingSoftCleaner/KingSoftCleaner.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/Email/Email.apk to out/ZIP/system/app/Email/Email.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/SpacesPolicyApp/SpacesPolicyApp.apk to out/ZIP/system/app/SpacesPolicyApp/SpacesPolicyApp.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/GuardProvider/GuardProvider.apk to out/ZIP/system/app/GuardProvider/GuardProvider.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/TranslationService/TranslationService.apk to out/ZIP/system/app/TranslationService/TranslationService.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/Mipay/Mipay.apk to out/ZIP/system/app/Mipay/Mipay.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/NetworkAssistant2/NetworkAssistant2.apk to out/ZIP/system/app/NetworkAssistant2/NetworkAssistant2.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/AntiSpam/AntiSpam.apk to out/ZIP/system/app/AntiSpam/AntiSpam.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/PerfTurbo/PerfTurbo.apk to out/ZIP/system/app/PerfTurbo/PerfTurbo.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/SmsExtra/SmsExtra.apk to out/ZIP/system/app/SmsExtra/SmsExtra.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/XiaomiVip/XiaomiVip.apk to out/ZIP/system/app/XiaomiVip/XiaomiVip.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/MiuiSuperMarket/MiuiSuperMarket.apk to out/ZIP/system/app/MiuiSuperMarket/MiuiSuperMarket.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/Provision/Provision.apk to out/ZIP/system/app/Provision/Provision.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/MiPlay/MiPlay.apk to out/ZIP/system/app/MiPlay/MiPlay.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/UpnpService/UpnpService.apk to out/ZIP/system/app/UpnpService/UpnpService.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/AppIndexProvider/AppIndexProvider.apk to out/ZIP/system/app/AppIndexProvider/AppIndexProvider.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/mab/mab.apk to out/ZIP/system/app/mab/mab.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/Whetstone/Whetstone.apk to out/ZIP/system/app/Whetstone/Whetstone.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/XiaomiAccount/XiaomiAccount.apk to out/ZIP/system/app/XiaomiAccount/XiaomiAccount.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/AMAPNetworkLocation/AMAPNetworkLocation.apk to out/ZIP/system/app/AMAPNetworkLocation/AMAPNetworkLocation.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/Calculator/Calculator.apk to out/ZIP/system/app/Calculator/Calculator.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/MiDrive/MiDrive.apk to out/ZIP/system/app/MiDrive/MiDrive.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/PowerKeeper/PowerKeeper.apk to out/ZIP/system/app/PowerKeeper/PowerKeeper.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/MiuiVideo/MiuiVideo.apk to out/ZIP/system/app/MiuiVideo/MiuiVideo.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/UserDictionaryProvider/UserDictionaryProvider.apk to out/ZIP/system/app/UserDictionaryProvider/UserDictionaryProvider.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/XMPass/XMPass.apk to out/ZIP/system/app/XMPass/XMPass.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/FileExplorer/FileExplorer.apk to out/ZIP/system/app/FileExplorer/FileExplorer.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/miui/miui.apk to out/ZIP/system/app/miui/miui.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/CaptivePortalLogin/CaptivePortalLogin.apk to out/ZIP/system/app/CaptivePortalLogin/CaptivePortalLogin.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/MiuiScanner/MiuiScanner.apk to out/ZIP/system/app/MiuiScanner/MiuiScanner.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/Metok/Metok.apk to out/ZIP/system/app/Metok/Metok.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/XiaomiSimActivateService/XiaomiSimActivateService.apk to out/ZIP/system/app/XiaomiSimActivateService/XiaomiSimActivateService.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/MiLivetalk/MiLivetalk.apk to out/ZIP/system/app/MiLivetalk/MiLivetalk.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/XiaomiServiceFramework/XiaomiServiceFramework.apk to out/ZIP/system/app/XiaomiServiceFramework/XiaomiServiceFramework.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/MiWallpaper/MiWallpaper.apk to out/ZIP/system/app/MiWallpaper/MiWallpaper.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/SystemBaseFunctions/SystemBaseFunctions.apk to out/ZIP/system/app/SystemBaseFunctions/SystemBaseFunctions.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/Updater/Updater.apk to out/ZIP/system/app/Updater/Updater.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/HTMLViewer/HTMLViewer.apk to out/ZIP/system/app/HTMLViewer/HTMLViewer.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/SecurityCoreAdd/SecurityCoreAdd.apk to out/ZIP/system/app/SecurityCoreAdd/SecurityCoreAdd.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/SoundRecorder/SoundRecorder.apk to out/ZIP/system/app/SoundRecorder/SoundRecorder.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/Notes/Notes.apk to out/ZIP/system/app/Notes/Notes.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/TouchAssistant/TouchAssistant.apk to out/ZIP/system/app/TouchAssistant/TouchAssistant.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/SSCMService/SSCMService.apk to out/ZIP/system/app/SSCMService/SSCMService.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/FM/FM.apk to out/ZIP/system/app/FM/FM.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/VoiceAssist/VoiceAssist.apk to out/ZIP/system/app/VoiceAssist/VoiceAssist.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/BluetoothMidiService/BluetoothMidiService.apk to out/ZIP/system/app/BluetoothMidiService/BluetoothMidiService.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/AnalyticsCore/AnalyticsCore.apk to out/ZIP/system/app/AnalyticsCore/AnalyticsCore.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/MiLinkService/MiLinkService.apk to out/ZIP/system/app/MiLinkService/MiLinkService.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/DeskClock/DeskClock.apk to out/ZIP/system/app/DeskClock/DeskClock.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/ApplicationsProvider/ApplicationsProvider.apk to out/ZIP/system/app/ApplicationsProvider/ApplicationsProvider.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/PersonalAssistantPlugin/PersonalAssistantPlugin.apk to out/ZIP/system/app/PersonalAssistantPlugin/PersonalAssistantPlugin.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/SpacesCore/SpacesCore.apk to out/ZIP/system/app/SpacesCore/SpacesCore.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/miuisystem/miuisystem.apk to out/ZIP/system/app/miuisystem/miuisystem.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/BugReport/BugReport.apk to out/ZIP/system/app/BugReport/BugReport.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/GameCenter/GameCenter.apk to out/ZIP/system/app/GameCenter/GameCenter.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/SystemAdSolution/SystemAdSolution.apk to out/ZIP/system/app/SystemAdSolution/SystemAdSolution.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/CloudService/CloudService.apk to out/ZIP/system/app/CloudService/CloudService.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/KSICibaEngine/KSICibaEngine.apk to out/ZIP/system/app/KSICibaEngine/KSICibaEngine.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/LiveWallpapersPicker/LiveWallpapersPicker.apk to out/ZIP/system/app/LiveWallpapersPicker/LiveWallpapersPicker.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/MiuiBluetooth/MiuiBluetooth.apk to out/ZIP/system/app/MiuiBluetooth/MiuiBluetooth.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/SecurityAdd/SecurityAdd.apk to out/ZIP/system/app/SecurityAdd/SecurityAdd.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/DocumentsUI/DocumentsUI.apk to out/ZIP/system/app/DocumentsUI/DocumentsUI.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/ThemeManager/ThemeManager.apk to out/ZIP/system/app/ThemeManager/ThemeManager.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/PaymentService/PaymentService.apk to out/ZIP/system/app/PaymentService/PaymentService.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/SogouInput/SogouInput.apk to out/ZIP/system/app/SogouInput/SogouInput.apk
Copy: /home/eternal-will/patchrom/miui/system/app/XHDPI/MiuiCompass/MiuiCompass.apk to out/ZIP/system/app/MiuiCompass/MiuiCompass.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/SecurityCenter/SecurityCenter.apk to out/ZIP/system/priv-app/SecurityCenter/SecurityCenter.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/Weather/Weather.apk to out/ZIP/system/priv-app/Weather/Weather.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/Browser/Browser.apk to out/ZIP/system/priv-app/Browser/Browser.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/Music/Music.apk to out/ZIP/system/priv-app/Music/Music.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/QuickSearchBox/QuickSearchBox.apk to out/ZIP/system/priv-app/QuickSearchBox/QuickSearchBox.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/AuthManager/AuthManager.apk to out/ZIP/system/priv-app/AuthManager/AuthManager.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/MiuiSystemUI/MiuiSystemUI.apk to out/ZIP/system/priv-app/MiuiSystemUI/MiuiSystemUI.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/MiuiCamera/MiuiCamera.apk to out/ZIP/system/priv-app/MiuiCamera/MiuiCamera.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/Contacts/Contacts.apk to out/ZIP/system/priv-app/Contacts/Contacts.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/Telecom/Telecom.apk to out/ZIP/system/priv-app/Telecom/Telecom.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/YellowPage/YellowPage.apk to out/ZIP/system/priv-app/YellowPage/YellowPage.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/DefaultContainerService/DefaultContainerService.apk to out/ZIP/system/priv-app/DefaultContainerService/DefaultContainerService.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/CarrierConfig/CarrierConfig.apk to out/ZIP/system/priv-app/CarrierConfig/CarrierConfig.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/VpnDialogs/VpnDialogs.apk to out/ZIP/system/priv-app/VpnDialogs/VpnDialogs.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/ContactsProvider/ContactsProvider.apk to out/ZIP/system/priv-app/ContactsProvider/ContactsProvider.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/DownloadProviderUi/DownloadProviderUi.apk to out/ZIP/system/priv-app/DownloadProviderUi/DownloadProviderUi.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/PersonalAssistant/PersonalAssistant.apk to out/ZIP/system/priv-app/PersonalAssistant/PersonalAssistant.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/StatementService/StatementService.apk to out/ZIP/system/priv-app/StatementService/StatementService.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/WeatherProvider/WeatherProvider.apk to out/ZIP/system/priv-app/WeatherProvider/WeatherProvider.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/Backup/Backup.apk to out/ZIP/system/priv-app/Backup/Backup.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/CleanMaster/CleanMaster.apk to out/ZIP/system/priv-app/CleanMaster/CleanMaster.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/CallLogBackup/CallLogBackup.apk to out/ZIP/system/priv-app/CallLogBackup/CallLogBackup.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/CalendarProvider/CalendarProvider.apk to out/ZIP/system/priv-app/CalendarProvider/CalendarProvider.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/MiDrop/MiDrop.apk to out/ZIP/system/priv-app/MiDrop/MiDrop.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/PackageInstaller/PackageInstaller.apk to out/ZIP/system/priv-app/PackageInstaller/PackageInstaller.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/DownloadProvider/DownloadProvider.apk to out/ZIP/system/priv-app/DownloadProvider/DownloadProvider.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/Calendar/Calendar.apk to out/ZIP/system/priv-app/Calendar/Calendar.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/MiuiKeyguard/MiuiKeyguard.apk to out/ZIP/system/priv-app/MiuiKeyguard/MiuiKeyguard.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/FindDevice/FindDevice.apk to out/ZIP/system/priv-app/FindDevice/FindDevice.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/MiuiGallery/MiuiGallery.apk to out/ZIP/system/priv-app/MiuiGallery/MiuiGallery.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/TeleService/TeleService.apk to out/ZIP/system/priv-app/TeleService/TeleService.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/Settings/Settings.apk to out/ZIP/system/priv-app/Settings/Settings.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/MiuiVoip/MiuiVoip.apk to out/ZIP/system/priv-app/MiuiVoip/MiuiVoip.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/TelephonyProvider/TelephonyProvider.apk to out/ZIP/system/priv-app/TelephonyProvider/TelephonyProvider.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/WallpaperCropper/WallpaperCropper.apk to out/ZIP/system/priv-app/WallpaperCropper/WallpaperCropper.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/Mms/Mms.apk to out/ZIP/system/priv-app/Mms/Mms.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/CloudBackup/CloudBackup.apk to out/ZIP/system/priv-app/CloudBackup/CloudBackup.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/SpacesManagerService/SpacesManagerService.apk to out/ZIP/system/priv-app/SpacesManagerService/SpacesManagerService.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/InCallUI/InCallUI.apk to out/ZIP/system/priv-app/InCallUI/InCallUI.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/MediaProvider/MediaProvider.apk to out/ZIP/system/priv-app/MediaProvider/MediaProvider.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/MiGameCenterSDKService/MiGameCenterSDKService.apk to out/ZIP/system/priv-app/MiGameCenterSDKService/MiGameCenterSDKService.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/MmsService/MmsService.apk to out/ZIP/system/priv-app/MmsService/MmsService.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/Mipub/Mipub.apk to out/ZIP/system/priv-app/Mipub/Mipub.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/ManagedProvisioning/ManagedProvisioning.apk to out/ZIP/system/priv-app/ManagedProvisioning/ManagedProvisioning.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/SettingsProvider/SettingsProvider.apk to out/ZIP/system/priv-app/SettingsProvider/SettingsProvider.apk
Copy: /home/eternal-will/patchrom/miui/system/priv-app/XHDPI/MiuiHome/MiuiHome.apk to out/ZIP/system/priv-app/MiuiHome/MiuiHome.apk
make: *** No rule to make target 'stockrom/system/framework/framework-res.apk', needed by 'out/framework-res.apk'.  Stop.`

**I'm getting this error everytime I give "make fullota" command**
Please help me
