### ISSUE TITLE
Bootloop help please

### ISSUE THREAD

**Issue by cuong95nddev** [MiCode/patchrom#136]
I am trying to patch miui base on cm13 for my device but get bootloop.
Here my log
> 01-01 00:19:06.263 5091-5091/? I/ServiceManager: Waiting for service media.camera.proxy...
01-01 00:19:06.287 5092-5092/? I/art: VMRuntime.preloadDexCaches strings total=311906 before=53011 after=53011
01-01 00:19:06.287 5092-5092/? I/art: VMRuntime.preloadDexCaches types total=27955 before=9490 after=9609
01-01 00:19:06.287 5092-5092/? I/art: VMRuntime.preloadDexCaches fields total=123666 before=38784 after=39898
01-01 00:19:06.287 5092-5092/? I/art: VMRuntime.preloadDexCaches methods total=212490 before=82873 after=85307
01-01 00:19:06.287 5092-5092/? I/art: VMRuntime.preloadDexCaches finished
01-01 00:19:06.288 5092-5092/? D/ThemeCompatibility: START loading theme compatibility config.
01-01 00:19:06.289 5092-5092/? D/ThemeCompatibility: getVersion(): /data/system/theme_config/theme_compatibility.xml  java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
01-01 00:19:06.291 5092-5092/? D/ThemeCompatibility: getConfigDocumentTree(): 130 vs -1
01-01 00:19:06.291 5092-5092/? D/ThemeCompatibility:     parse file: /system/media/theme/theme_compatibility.xml
01-01 00:19:06.293 5092-5092/? D/ThemeCompatibility:     invalid file format: /system/media/theme/theme_compatibility.xml -- org.xml.sax.SAXParseException: Comments may not contain -- (position:COMMENT @11:10 in java.io.InputStreamReader@b854b56) 
01-01 00:19:06.294 5092-5092/? D/ThemeCompatibility:     parse file: null
01-01 00:19:06.295 5092-5092/? D/ThemeCompatibility:     invalid file format: null -- java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
01-01 00:19:06.295 5092-5092/? D/ThemeCompatibility: END loading: version=-1 size=0
01-01 00:19:06.321 5264-5264/? D/idmap: error: no read access to /vendor/overlay: No such file or directory
01-01 00:19:06.339 5092-5092/? I/Zygote: Preloading resources...
01-01 00:19:06.391 5092-5092/? W/Resources: Preloaded drawable resource #0x1080096 (android:drawable/toast_frame) that varies with configuration!!
01-01 00:19:06.415 5092-5092/? I/Zygote: ...preloaded 86 resources in 75ms.
01-01 00:19:06.415 5092-5092/? I/Zygote: ...preloaded 0 resources in 0ms.
01-01 00:19:06.417 5092-5092/? D/libEGL: loaded /vendor/lib/egl/libEGL_adreno.so
01-01 00:19:06.418 5092-5092/? D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_adreno.so
01-01 00:19:06.433 5092-5092/? D/libEGL: loaded /vendor/lib/egl/libGLESv2_adreno.so
01-01 00:19:06.440 5092-5092/? I/Zygote: Preloading shared libraries...
01-01 00:19:06.446 5092-5092/? D/Zygote: end preload
01-01 00:19:06.446 5092-5092/? I/art: Starting a blocking GC Explicit
01-01 00:19:06.465 5092-5092/? I/art: Explicit concurrent mark sweep GC freed 34888(5MB) AllocSpace objects, 125(2MB) LOS objects, 39% free, 6MB/10MB, paused 168us total 18.680ms
01-01 00:19:06.467 5092-5153/? E/System: Uncaught exception thrown by finalizer
01-01 00:19:06.467 5092-5153/? E/System: java.lang.NullPointerException: Attempt to invoke virtual method 'void dalvik.system.CloseGuard.close()' on a null object reference
                                             at java.io.FileInputStream.close(FileInputStream.java:113)
                                             at java.io.FileInputStream.finalize(FileInputStream.java:140)
                                             at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:202)
                                             at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:185)
                                             at java.lang.Thread.run(Thread.java:818)
01-01 00:19:06.468 5092-5092/? I/art: Starting a blocking GC Explicit
01-01 00:19:06.474 5092-5092/? I/art: Explicit concurrent mark sweep GC freed 675(33KB) AllocSpace objects, 1(28KB) LOS objects, 39% free, 6MB/10MB, paused 173us total 5.315ms
01-01 00:19:06.474 5092-5155/? I/art: Starting a blocking GC HeapTrim
01-01 00:19:06.478 5092-5092/? I/art: Starting a blocking GC Background
01-01 00:19:06.517 5092-5092/? I/Zygote: System server process 5287 has been created
01-01 00:19:06.518 5092-5092/? I/Zygote: Accepting command socket connections
01-01 00:19:06.525 5287-5287/? I/InstallerConnection: connecting...
01-01 00:19:06.527 287-287/? I/installd: new connection
01-01 00:19:06.533 5287-5287/? I/InstallerConnection: disconnecting...
01-01 00:19:06.533 287-287/? E/installd: eof
01-01 00:19:06.533 287-287/? E/installd: failed to read size
01-01 00:19:06.533 287-287/? I/installd: closing connection
01-01 00:19:06.562 5287-5287/? I/art: Verification error in void com.android.server.SystemServer.startOtherServices()
01-01 00:19:06.562 5287-5287/? I/art: void com.android.server.SystemServer.startOtherServices() failed to verify: void com.android.server.SystemServer.startOtherServices(): [0x19C] register v3 has type Precise Reference: java.lang.String but expected Reference: android.os.Handler
01-01 00:19:06.563 5287-5287/? W/art: Verification failed on class com.android.server.SystemServer in /system/framework/services.jar because: Verifier rejected class com.android.server.SystemServer due to bad method void com.android.server.SystemServer.startOtherServices()
01-01 00:19:06.563 5287-5287/? D/AndroidRuntime: Shutting down VM
01-01 00:19:06.564 5287-5287/? E/AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
                                                 java.lang.VerifyError: Verifier rejected class com.android.server.SystemServer due to bad method void com.android.server.SystemServer.startOtherServices() (declaration of 'com.android.server.SystemServer' appears in /system/framework/services.jar)
                                                     at java.lang.Class.classForName(Native Method)
                                                     at java.lang.Class.forName(Class.java:324)
                                                     at com.android.internal.os.RuntimeInit.invokeStaticMain(RuntimeInit.java:208)
                                                     at com.android.internal.os.RuntimeInit.applicationInit(RuntimeInit.java:331)
                                                     at com.android.internal.os.RuntimeInit.zygoteInit(RuntimeInit.java:283)
                                                     at com.android.internal.os.ZygoteInit.handleSystemServerProcess(ZygoteInit.java:458)
                                                     at com.android.internal.os.ZygoteInit.startSystemServer(ZygoteInit.java:545)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
01-01 00:19:06.565 5287-5287/? E/AndroidRuntime: Error reporting crash
                                                 java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.IActivityManager.handleApplicationCrash(android.os.IBinder, android.app.ApplicationErrorReport$CrashInfo)' on a null object reference
                                                     at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:95)
                                                     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

**Comment by aymende7** [comment]
same problem
