### ISSUE TITLE
Cannot sync MiCode git repo

### ISSUE THREAD

**Issue by pyroemaniac** [MiCode/patchrom#15]
I have set everything up but when i type "repo sync" the following errors occur

"josh@josh:~/patchrom$ repo sync
fatal: '../MiCode/patchrom_android.git' does not appear to be a git repository
fatal: The remote end hung up unexpectedly
error: Cannot fetch MiCode/patchrom_android"

any help on this would be greatly appreciated.

**Comment by iBotPeaches** [comment]
Then you don't have the REPO there. This a support problem, not an issue. You missed the first few steps of the tutorial where you actually start the REPO.
