### ISSUE TITLE
make: *** [out/services.jar] Error 1

### ISSUE THREAD

**Issue by pyroemaniac** [MiCode/patchrom#16]
having trouble with making the services.jar build, something to do with the smali

/home/josh/patchrom/tools/apktool --quiet b out/services out/services.jar
Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: java.io.FileInputStream@d3bef50
    at brut.androlib.src.DexFileBuilder.addSmaliFile(DexFileBuilder.java:45)
    at brut.androlib.src.DexFileBuilder.addSmaliFile(DexFileBuilder.java:33)
    at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:64)
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:48)
    at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:35)
    at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:222)
    at brut.androlib.Androlib.buildSources(Androlib.java:179)
    at brut.androlib.Androlib.build(Androlib.java:170)
    at brut.androlib.Androlib.build(Androlib.java:154)
    at brut.apktool.Main.cmdBuild(Main.java:182)
    at brut.apktool.Main.main(Main.java:67)
make: **\* [out/services.jar] Error 1

If someone can point me in the right direction to fix this, it would be appreciated greatly.

**Comment by yu88my** [comment]
Please try this command "../tools/smali services.jar.out", and send me the log.

**Comment by pyroemaniac** [comment]
Thank you for the reply, this is the output:

josh@ubuntu:~$ cd patchrom
josh@ubuntu:~/patchrom$ cd rezound
josh@ubuntu:~/patchrom/rezound$ ../tools/smali services.jar.out
services.jar.out/smali/com/android/server/am/ActivityManagerService.smali[76683,4] Label cond_b has multiple defintions.

**Comment by yu88my** [comment]
did you change the ActivityManagerService.smali in services.jar.out? about line 76683, there are more than one "cond_b".

**Comment by pyroemaniac** [comment]
That's the problem, there aren't that many lines in that file

**Comment by yu88my** [comment]
Did you resolve the problem?

**Comment by pyroemaniac** [comment]
No, I accidently pressed close on my phone.

**Comment by yu88my** [comment]
Can you send me the ActivityManagerService.smali? let my try. My emali is yumingyang@xiaomi.com

**Comment by pyroemaniac** [comment]
Alright ill be home in about 10 minutes, will you be on?

**Comment by yu88my** [comment]
Yeah, take it easy.

**Comment by pyroemaniac** [comment]
file sent from pyroemaniac@gmail.com

**Comment by yu88my** [comment]
There are two con_b in line 76683 and line 76601 in method "updateConfigurationLocked", I had modified the file and sent to you.

**Comment by pyroemaniac** [comment]
Thank you for being patient with me, I looked at what you modified and applied it to all relating errors afterwards. I am now much closer to making a working MIUI. Thank you!

**Comment by yu88my** [comment]
Thanks your support for MIUI.

**Comment by cmartinbaughman** [comment]
If you don't mind me asking, what exactly was the way you fixed this? I have the exact same issue, same method "updateConfigurationLocked, just slightly different line numbers.

**Comment by yu88my** [comment]
you can compare your smali code with google's, and change one :con_b pair to another unique label, you must keep the logic right.

**Comment by cmartinbaughman** [comment]
Thank you so much for responding. I am developing this for the HTC Evo 3d. I've already put out a "ported" version, but now I want to give the community the "real-deal" from MiCode. Fantastic project, and I can't wait to get this working so I can grab your latest updates straight from here. Thanks again yu88my!
