### ISSUE TITLE
help with boot.img (i9100)

### ISSUE THREAD

**Issue by vauss** [MiCode/patchrom#21]
i'm trying to compile with XWLPG base (latest european firmware) but the rom only works with original miui boot.img (ZSLPG)
patchrom renames original zImage to boot.img (without changes) but doesnt work

should i make changes on it before use patchrom?
what can i do?

thanks!!!

**Comment by fanoge** [comment]
if you just want to use the boot image from XWLPG, you could just get zImage from XWLPG and save it as stockrom/boot.img. (although I am not sure if the image from XWLPG works since i9100 currently is ported from ZSLPG).

**Comment by vauss** [comment]
thanks fanoge but didn't work

seems that boot.img (miui zslpg) was modified because original zImage (from ZSLPG) size is 8 mb but boot.img size is 5.5mb

i think zimage file needs some changes....

**Comment by fanoge** [comment]
yes, some changes are made to the kernel , you could use repack tool (from https://github.com/xiaolu/galaxys2_kernel_repack) to see the changes to the ramdisk (init.rc, default.prop and so on).

**Comment by vauss** [comment]
thanks again!!!

now boots XWLPG ;)
