### ISSUE TITLE
make: *** [out/MiuiSystemUI.apk] Error 1 

### ISSUE THREAD

**Issue by jcorrea86** [MiCode/patchrom#22]
I keep getting this error when trying to run make fullota:

/home/jr/stspatchrom/tools/apktool --quiet d -f /home/jr/stspatchrom/miui/system/app/MiuiSystemUI.apk out/MiuiSystemUI
/home/jr/stspatchrom/tools/patch_miui_app.sh >/dev/null MiuiSystemUI out/MiuiSystemUI

> > > build out/MiuiSystemUI.apk...
> > > cp: cannot stat `MiuiSystemUI': No such file or directory
> > > make: **\* [out/MiuiSystemUI.apk] Error 1

I noticed on the Makefile the following line.  If I hash it out, then the rom builds, but how would I fix this to buildout and compile these files?

local-miui-modified-apps := MiuiSystemUI MiuiHome Mms Phone Settings

-Jr

**Comment by yu88my** [comment]
If you dont need to modify the MiuiSystemUI, just remove it from local-miui-modified-apps in makefile.

**Comment by jcorrea86** [comment]
so... I can skip those files?

**Comment by yu88my** [comment]
yes you can.
