### ISSUE TITLE
default.xml

### ISSUE THREAD

**Issue by SeKi81** [MiCode/patchrom#29]
Hey,

all paths are wrong!

**Comment by yu88my** [comment]
sorry, i had updated the right default.xml. you can pull it.

---

发件人: Kalashnikitty [notifications@github.com]
发送时间: 2012年8月10日 17:39
到: MiCode/patchrom
主题: [patchrom] default.xml (#29)

Hey,

all paths are wrong!

**Comment by SeKi81** [comment]
Thank you :)
