### ISSUE TITLE
 MiCode/patchrom_i9300 is not a valid repository name

### ISSUE THREAD

**Issue by jmoney4769** [MiCode/patchrom#30]
I'm trying to setup a build environment on my linux machine using the instructions provided by the patchrom README.  However, when I try to use "repo sync," I get an error saying "Fetching projects:  95% (19/20)  fatal: remote error: 
   MiCode/patchrom_i9300 is not a valid repository name
  Email support@github.com for help
error: Cannot fetch  MiCode/patchrom_i9300"

Any idea what I can do to fix this?

**Comment by yu88my** [comment]
I had fixed this, you can try again.

**Comment by jmoney4769** [comment]
Alright, that works, but when following instructions, there is no tools/ directory.  All I have is android/, build/, .repo/, and shadow/ (the device I am trying to port MIUI to).  When syncing, I get the error "error: revision refs/heads/ics in MiCode/patchrom-gnote not found."  Are directories just disappearing or something?  Is this a similar problem?

**Comment by yu88my** [comment]
I had synced for 6 hours, it's to large too complete. when finishing, I will check out what's wrong, and send you the solution. Or you can delete the "gnote" line in your manifest.xml, and try to sync again.
