### ISSUE TITLE
Missing Directory and Files

### ISSUE THREAD

**Issue by cmartinbaughman** [MiCode/patchrom#32]
After a recent commit I noticed that the miui/src directory was removed. Unfortunately when I try to buildthe x515m or i9100 projects they die with the exact same error:

> > > Install framework resources for apktool...
> > > Sep 6, 2012 4:28:34 PM brut.androlib.res.AndrolibResources installFramework
> > > INFO: Framework installed to: /root/apktool/framework/2.apk
> > > Sep 6, 2012 4:28:34 PM brut.androlib.res.AndrolibResources installFramework
> > > INFO: Framework installed to: /root/apktool/framework/5.apk
> > > Sep 6, 2012 4:28:35 PM brut.androlib.res.AndrolibResources installFramework
> > > INFO: Framework installed to: /root/apktool/framework/4.apk
> > > Sep 6, 2012 4:28:35 PM brut.androlib.res.AndrolibResources installFramework
> > > INFO: Framework installed to: /root/apktool/framework/3.apk
> > > install framework-miui-res.apk
> > > /mnt/micode/tools/apktool --verbose if /mnt/micode/miui/system/framework/framework-miui-res.apk
> > > Sep 6, 2012 4:28:35 PM brut.androlib.res.AndrolibResources installFramework
> > > INFO: Framework installed to: /root/apktool/framework/6.apk
> > > unzip  stockrom.zip "system/framework/_.apk" -d out
> > > Archive:  stockrom.zip
> > >   inflating: out/system/framework/twframework-res.apk
> > >   inflating: out/system/framework/framework-res.apk
> > > install out/system/framework/twframework-res.apk
> > > Sep 6, 2012 4:28:36 PM brut.androlib.res.AndrolibResources installFramework
> > > INFO: Framework installed to: /root/apktool/framework/2.apk
> > > install out/system/framework/framework-res.apk
> > > Sep 6, 2012 4:28:37 PM brut.androlib.res.AndrolibResources installFramework
> > > INFO: Framework installed to: /root/apktool/framework/1.apk
> > > <<< install framework resources completed!
> > > build out/framework-res.apk...
> > > add miui overlay resources
> > > ls: cannot access /mnt/micode/miui/src/frameworks/miui/overlay/frameworks/base/core/res/res/[^v]_: No such file or directory
> > > ls: cannot access /mnt/micode/miui/src/frameworks/miui/overlay/frameworks/base/core/res/res/values_: No such file or directory
> > > /mnt/micode/tools/remove_redef.py  out/framework-res
> > > /mnt/micode/tools/apktool --verbose b out/framework-res out/framework-res.apk
> > > Sep 6, 2012 4:28:40 PM brut.androlib.Androlib buildSources
> > > WARNING: Could not find sources
> > > Sep 6, 2012 4:28:40 PM brut.androlib.Androlib buildResourcesFull
> > > INFO: Checking whether resources has changed...
> > > Sep 6, 2012 4:28:40 PM brut.androlib.Androlib buildResourcesFull
> > > INFO: Building resources...
> > > aapt: warning: string 'policydesc_allow_htmlemail' has no default translation in /mnt/micode/i9100/out/framework-res/res; found: en_US
> > > aapt: warning: string 'policylab_allow_htmlemail' has no default translation in /mnt/micode/i9100/out/framework-res/res; found: en_US
> > > aapt: warning: string 'wifi_p2p_pbc_go_negotiation_request_message' has no default translation in /mnt/micode/i9100/out/framework-res/res; found: en_GB
> > > aapt: warning: string 'wifi_p2p_pin_display_message' has no default translation in /mnt/micode/i9100/out/framework-res/res; found: en_GB
> > > aapt: warning: string 'wifi_p2p_pin_go_negotiation_request_message' has no default translation in /mnt/micode/i9100/out/framework-res/res; found: en_GB
> > > aapt: warning: string 'zzz_skt_usim_not_used' has no default translation in /mnt/micode/i9100/out/framework-res/res; found: zh_HK zh_TW
> > > Sep 6, 2012 4:28:53 PM brut.androlib.Androlib buildApk
> > > INFO: Building apk file...
> > > /mnt/micode/tools/apktool --verbose if out/framework-res.apk
> > > Sep 6, 2012 4:28:56 PM brut.androlib.res.AndrolibResources installFramework
> > > INFO: Framework installed to: /root/apktool/framework/1.apk
> > > <<< build out/framework-res.apk completed!
> > > build out/framework-miui-res.apk...
> > > /mnt/micode/tools/apktool --verbose d -f /mnt/micode/miui/system/framework/framework-miui-res.apk out/framework-miui-res
> > > Sep 6, 2012 4:28:56 PM brut.androlib.res.AndrolibResources loadMainPkg
> > > INFO: Loading resource table...
> > > Sep 6, 2012 4:28:57 PM brut.androlib.res.AndrolibResources loadMainPkg
> > > INFO: Loaded.
> > > Sep 6, 2012 4:28:57 PM brut.androlib.res.AndrolibResources loadFrameworkPkg
> > > INFO: Loading resource table from file: /root/apktool/framework/1.apk
> > > Sep 6, 2012 4:28:58 PM brut.androlib.res.AndrolibResources loadFrameworkPkg
> > > INFO: Loaded.
> > > Sep 6, 2012 4:28:58 PM brut.androlib.res.AndrolibResources decode
> > > INFO: Decoding file-resources...
> > > Sep 6, 2012 4:29:02 PM brut.androlib.res.AndrolibResources decode
> > > INFO: Decoding values_/\* XMLs...
> > > Sep 6, 2012 4:29:02 PM brut.androlib.res.AndrolibResources decode
> > > INFO: Done.
> > > Sep 6, 2012 4:29:02 PM brut.androlib.Androlib decodeRawFiles
> > > INFO: Copying assets and libs...
> > > cp: cannot stat `/mnt/micode/miui/src/frameworks/miui/core/res/res': No such file or directory
> > > make: **\* [out/framework-miui-res.apk] Error 1

Are there any plans to put this back? Is the build process changing? 

Thanks!

CMBaughman

**Comment by yu88my** [comment]
This had been put back. Pls sync again.

**Comment by cmartinbaughman** [comment]
As always, thank you for your prompt action! I've resync'd and built everything is looking good. Thanks yu88my!
