### ISSUE TITLE
Issue on signing files

### ISSUE THREAD

**Issue by sijav** [MiCode/patchrom#48]
This error apear after I updated my ubuntu and restarted

> > Sign target files
> >     signing: Userbook.apk                                   (/home/sijav/patchrom/build/security/platform)
> > Traceback (most recent call last):
> >   File "/home/sijav/patchrom/tools/releasetools/sign_target_files_apks", line 354, in <module>
> >     main(sys.argv[1:])
> >   File "/home/sijav/patchrom/tools/releasetools/sign_target_files_apks", line 341, in main
> >     SignApks(input_zip, output_zip, apk_key_map, key_passwords)
> >   File "/home/sijav/patchrom/tools/releasetools/sign_target_files_apks", line 153, in SignApks
> >     signed_data = SignApk(data, key, key_passwords[key])
> >   File "/home/sijav/patchrom/tools/releasetools/sign_target_files_apks", line 131, in SignApk
> >     common.SignFile(unsigned.name, signed.name, keyname, pw, align=4)
> >   File "/home/sijav/patchrom/tools/releasetools/common.py", line 374, in SignFile
> >     p = Run(["zipalign", "-f", str(align), sign_name, output_name])
> >   File "/home/sijav/patchrom/tools/releasetools/common.py", line 62, in Run
> >     return subprocess.Popen(args, **kwargs)
> >   File "/usr/lib/python2.7/subprocess.py", line 679, in **init**
> >     errread, errwrite)
> >   File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
> >     raise child_exception
> > OSError: [Errno 2] No such file or directory
> > I'm currently runnung 64bit ubuntu 12.04 LTS with 4 GB of ram and a Core 2 Quad CPU running at 2.66 Ghz,
> > I have installed pyton but the problem is still is!
> > any kind of help would be much appreciate.
> > thnx

**Comment by teoking** [comment]
The build error is explained by this message:
OSError: [Errno 2] No such file or directory

So it's easy to know that you have no zipalign was include in the path.
You can use 'which zipalign' to detect if zipalign is already contained in the path.

So try this:
export PATH=$PATH:$YOUR_ANDROID_HOME_PATH/tools

then try:
make fullota

**Comment by sijav** [comment]
Thanks
