### ISSUE TITLE
Manually resolving conflicts.

### ISSUE THREAD

**Issue by iBotPeaches** [MiCode/patchrom#5]
Okay, so I've taken the file and it says resolve problems.

I see the 

-dst_smali-orig
-dst_smali_patched
-new_smali
-old_smali
-reject

Do I apply the manual fixes to new_smali? Or to the files outside of /temp in the root of my porting phone.

Also, could you shed some light for a novice on how exactly to read the smali diff files? Do we want to match the asteriks (*) or the hyphens (-)?

EX:
``` **\* PhoneWindowManager$18.smali 2012-03-19 22:44:52.367030112 -0500
--- PhoneWindowManager$18.smali 2012-03-19 22:43:58.951031278 -0500

---

**\* 42,48 ****

  # virtual methods
  .method public run()V
!     .locals 5

```
  .prologue
  const/4 v4, 0x0
```

--- 42,48 ----

  # virtual methods
  .method public run()V
!     .locals 6

``````
  .prologue
  const/4 v4, 0x0```
``````

So does this mean I go to line 42-48 and replace the .locals 6 to .locals 5?

**Comment by MiuiAnderson** [comment]
Yes, you must manually resolve the conflict which is list in the reject dir.

---

发件人: Connor Tumbleson [reply@reply.github.com]
发送时间: 2012年3月20日 20:53
到: 汪文俊
主题: [patchrom] Manually resolving conflicts. (#5)

Okay, so I've taken the file and it says resolve problems.

I see the

-dst_smali-orig
-dst_smali_patched
-new_smali
-old_smali
-reject

Do I apply the manual fixes to new_smali? Or to the files outside of /temp in the root of my porting phone.

---

Reply to this email directly or view it on GitHub:
https://github.com/MiCode/patchrom/issues/5
