### ISSUE TITLE
Issue with make fullota

### ISSUE THREAD

**Issue by mathm2013** [MiCode/patchrom#68]
When i use make fullota and it starts to edit framework, i get this error:

> > > build out/framework-res.apk...
> > > # for call ./customize_framework-res.sh
> > > 
> > > nothing matches overlay file default_wallpaper.jpg, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file default_wallpaper.jpg, for flavor ,,,,,,,,,,,,xxhdpi,,,,,,,
> > > nothing matches overlay file ic_bullet_key_permission.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file ic_dialog_alert_holo_dark.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file ic_dialog_alert_holo_light.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file ic_media_video_poster.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file ic_text_dot.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file menu_hardkey_panel_holo_dark.9.png, for flavor ,,,,,,,,,land,,,hdpi,,,,,,,
> > > nothing matches overlay file menu_hardkey_panel_holo_light.9.png, for flavor ,,,,,,,,,land,,,hdpi,,,,,,,
> > > nothing matches overlay file pointer_spot_touch_icon.xml, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file pointer_spot_touch_icon.xml, for flavor ,,,,,,,,,,,,xxhdpi,,,,,,,
> > > nothing matches overlay file stat_notify_call_mute.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file stat_notify_missed_call.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file stat_notify_missed_call.png, for flavor ,,,,,,,,,,,,xxhdpi,,,,,,,
> > > nothing matches overlay file stat_notify_wifi_in_range.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file stat_sys_adb.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file stat_sys_adb.png, for flavor ,,,,,,,,,,,,xxhdpi,,,,,,,
> > > nothing matches overlay file stat_sys_download_anim0.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file stat_sys_download_anim0.png, for flavor ,,,,,,,,,,,,xxhdpi,,,,,,,
> > > nothing matches overlay file stat_sys_download_anim1.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file stat_sys_download_anim1.png, for flavor ,,,,,,,,,,,,xxhdpi,,,,,,,
> > > nothing matches overlay file stat_sys_download_anim2.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file stat_sys_download_anim2.png, for flavor ,,,,,,,,,,,,xxhdpi,,,,,,,
> > > nothing matches overlay file stat_sys_download_anim3.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file stat_sys_download_anim3.png, for flavor ,,,,,,,,,,,,xxhdpi,,,,,,,
> > > nothing matches overlay file stat_sys_download_anim4.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file stat_sys_download_anim4.png, for flavor ,,,,,,,,,,,,xxhdpi,,,,,,,
> > > nothing matches overlay file stat_sys_download_anim5.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file stat_sys_download_anim5.png, for flavor ,,,,,,,,,,,,xxhdpi,,,,,,,
> > > nothing matches overlay file stat_sys_speakerphone.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file stat_sys_tether_wifi.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file stat_sys_tether_wifi.png, for flavor ,,,,,,,,,,,,xxhdpi,,,,,,,
> > > nothing matches overlay file text_select_handle_left.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file text_select_handle_middle.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file text_select_handle_right.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file toast_frame.9.png, for flavor ,,,,,,,,,,,,xhdpi,,,,,,,
> > > nothing matches overlay file toast_frame.9.png, for flavor ,,,,,,,,,,,,xxhdpi,,,,,,,
> > > nothing matches overlay file task_close_enter.xml, for flavor ,,,,,,,,,port,,,,,,,,,,
> > > nothing matches overlay file task_close_exit.xml, for flavor ,,,,,,,,,port,,,,,,,,,,
> > > nothing matches overlay file task_open_enter.xml, for flavor ,,,,,,,,,port,,,,,,,,,,
> > > nothing matches overlay file task_open_exit.xml, for flavor ,,,,,,,,,port,,,,,,,,,,
> > > /home/matheus/patchrom/miui/src/miui/res-overlay/v5/platform/v19/frameworks/base/core/res/res/layout/keyguard_screen_password_portrait.xml:137: error: Error: No resource found that matches the given name (at 'src' with value '@drawable/ic_lockscreen_ime').
> > > make: **\* [out/framework-res.apk] Error 1
> > > Would anyone mind helping me?

**Comment by programmerlapar** [comment]
hi buddy.

are you fixed this problem?
can you tell me how to fix that

**Comment by zdunex25** [comment]
Just add such image to your drawable.
