### ISSUE TITLE
make fullota problem

### ISSUE THREAD

**Issue by ymg2006** [MiCode/patchrom#70]
hello every one .
im porting miui to mt6589 device ...
everything is ok but i got this error at the end .

<<< build out/framework-res.apk completed!

> > > build out/framework-miui-res.apk...
> > > /home/virtual/miui_patchrom/tools/apktool --quiet d -f -t miui /home/virtual/miui_patchrom/miui/XHDPI/system/framework/framework-miui-res.apk out/framework-miui-res
> > > <<< build out/framework-miui-res.apk completed!
> > > /home/virtual/miui_patchrom/tools/apktool --quiet d -f /home/virtual/miui_patchrom/miui/XHDPI/system/framework/services.jar out/services_miui
> > > build out/services.jar...
> > > /home/virtual/miui_patchrom/tools/add_miui_smail.sh >/dev/null out/services_miui out/services
> > > /home/virtual/miui_patchrom/tools/apktool --quiet b out/services out/services.jar
> > > [38312,4] The register number must be less than v16
> > > Exception in thread "main" brut.androlib.AndrolibException: Could not smali file: /home/virtual/miui_patchrom/lenovop780/out/services/smali/com/android/server/pm/PackageManagerService.smali
> > >     at brut.androlib.src.DexFileBuilder.addSmaliFile(DexFileBuilder.java:45)
> > >     at brut.androlib.src.DexFileBuilder.addSmaliFile(DexFileBuilder.java:33)
> > >     at brut.androlib.src.SmaliBuilder.buildFile(SmaliBuilder.java:66)
> > >     at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:50)
> > >     at brut.androlib.src.SmaliBuilder.build(SmaliBuilder.java:37)
> > >     at brut.androlib.Androlib.buildSourcesSmali(Androlib.java:257)
> > >     at brut.androlib.Androlib.buildSources(Androlib.java:214)
> > >     at brut.androlib.Androlib.build(Androlib.java:205)
> > >     at brut.androlib.Androlib.build(Androlib.java:176)
> > >     at brut.apktool.Main.cmdBuild(Main.java:228)
> > >     at brut.apktool.Main.main(Main.java:79)
> > > make: **\* [out/services.jar] Error 1

**Comment by kat0072** [comment]
Please make sure that you at using MIXED mode of JDK. I mean JDK 64bit.

---

kat0072@VPCSA35GG:~/patchrom$ java -version
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)

## Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)
