### ISSUE TITLE
diff files in decompiled jars

### ISSUE THREAD

**Issue by iBotPeaches** [MiCode/patchrom#8]
After running

"make firstpatch", all my jar files contain files like
PhoneWindow$DialogMenuCallback.smali-{line}.diff

for any file that was changed. I don't know if building these are ignored, but it doesn't seem right.

(Only seen in the new PatchRom). I deleted all and re-pulled and still duplicated the problem.

**Comment by fanoge** [comment]
Well, these {line}-diff files are used to restore the line information used
by rmline.sh, and you could just delete them by:
find /path/to/dir -name "*-{line}.diff" -exec rm {} \;

And we would refine the related scripts in future..

thanks

2012/3/24 Connor Tumbleson <
reply@reply.github.com
