### ISSUE TITLE
Errors on signing

### ISSUE THREAD

**Issue by iBotPeaches** [MiCode/patchrom#9]
Copy target file template into current working directory
Copy bootimage
Copy system dir
Process metadata
Recovery link files success
Compress the target_files dir into zip file
/home/peaches/patchrom/dhd/out/target_files
zip -q -r -y /home/peaches/patchrom/dhd/out/target_files.zip *
/home/peaches/patchrom/dhd
Sign target files
Traceback (most recent call last):
  File "/home/peaches/patchrom/tools/releasetools/sign_target_files_apks", line 354, in <module>
    main(sys.argv[1:])
  File "/home/peaches/patchrom/tools/releasetools/sign_target_files_apks", line 333, in main
    misc_info = common.LoadInfoDict(input_zip)
  File "/home/peaches/patchrom/tools/releasetools/common.py", line 144, in LoadInfoDict
    d["fstab"] = LoadRecoveryFSTab(zip)
  File "/home/peaches/patchrom/tools/releasetools/common.py", line 163, in LoadRecoveryFSTab
    raise ValueError("malformed recovery.fstab line: \"%s\"" % (line,))
ValueError: malformed recovery.fstab line: "/cache      ext4        /dev/block/mmcblk0p27   NULL    ext3"
Build full ota package: /home/peaches/patchrom/dhd/out/fullota.zip
unzipping target target-files...
warning [/home/peaches/patchrom/dhd/out/target_files.zip]:  zipfile is empty

   ERROR: failed to unzip input target-files "/home/peaches/patchrom/dhd/out/target_files.zip"

make: **\* [fullota] Error 1

My target_files.zip is like 102MB. This block of code

function sign_target_files {
    echo "Sign target files"
    $SIGN_TARGET_FILES_APKS -d $PORT_ROOT/build/security $TARGET_FILES_ZIP temp.zip
    mv temp.zip $TARGET_FILES_ZIP
}

Takes that zip, messes it up and outputs a 22byte ZIP file. I did the commands as follows

source build/envsetup.sh
cd dhd
make workspace
make firstpath
-fix rejects
-make fullota

This EXACT process worked fine on the previous build, and only boot-looped with errors described in previous bug reports. Please advise.

**Comment by MiuiAnderson** [comment]
oh, yes, this is a strict limit put by ota_from_target_files.

please check recovery.fstab under your metadata directory.

ensure each line is 3 columns

for example,

"/cache              ext4            /dev/block/mmcblk0p27   NULL    ext3"

should be "/cache ext4 /dev/block/mmcblk0p27"

---

发件人: Connor Tumbleson [reply@reply.github.com]
发送时间: 2012年3月24日 8:33
到: 汪文俊
主题: [patchrom] Errors on signing (#9)

Copy target file template into current working directory
Copy bootimage
Copy system dir
Process metadata
Recovery link files success
Compress the target_files dir into zip file
/home/peaches/patchrom/dhd/out/target_files
zip -q -r -y /home/peaches/patchrom/dhd/out/target_files.zip *
/home/peaches/patchrom/dhd
Sign target files
Traceback (most recent call last):
  File "/home/peaches/patchrom/tools/releasetools/sign_target_files_apks", line 354, in <module>
    main(sys.argv[1:])
  File "/home/peaches/patchrom/tools/releasetools/sign_target_files_apks", line 333, in main
    misc_info = common.LoadInfoDict(input_zip)
  File "/home/peaches/patchrom/tools/releasetools/common.py", line 144, in LoadInfoDict
    d["fstab"] = LoadRecoveryFSTab(zip)
  File "/home/peaches/patchrom/tools/releasetools/common.py", line 163, in LoadRecoveryFSTab
    raise ValueError("malformed recovery.fstab line: \"%s\"" % (line,))
ValueError: malformed recovery.fstab line: "/cache              ext4            /dev/block/mmcblk0p27   NULL    ext3"
Build full ota package: /home/peaches/patchrom/dhd/out/fullota.zip
unzipping target target-files...
warning [/home/peaches/patchrom/dhd/out/target_files.zip]:  zipfile is empty

   ERROR: failed to unzip input target-files "/home/peaches/patchrom/dhd/out/target_files.zip"

make: **\* [fullota] Error 1

My target_files.zip is like 102MB. This block of code

function sign_target_files {
    echo "Sign target files"
    $SIGN_TARGET_FILES_APKS -d $PORT_ROOT/build/security $TARGET_FILES_ZIP temp.zip
    mv temp.zip $TARGET_FILES_ZIP
}

Takes that zip, messes it up and outputs a 22byte ZIP file. I did the commands as follows

source build/envsetup.sh
cd dhd
make workspace
make firstpath
-fix rejects
-make fullota

This EXACT process worked fine on the previous build, and only boot-looped with errors described in previous bug reports. Please advise.

---

Reply to this email directly or view it on GitHub:
https://github.com/MiCode/patchrom/issues/9

**Comment by iBotPeaches** [comment]
Thank you.

The problem between the 1 SPACE vs 1 TAB, didn't seem to matter. It was the added NULL ext3 added onto some extra partitions that caused this. Removing those and ending with this:

```
# mount point fstype device [device2]
/recovery emmc /dev/block/mmcblk0p21
/boot emmc /dev/block/mmcblk0p22
/cache ext4 /dev/block/mmcblk0p27
/data ext4 /dev/block/mmcblk0p26
/sdcard vfat /dev/block/mmcblk1p1 /dev/block/mmcblk1
/system ext4 /dev/block/mmcblk0p25
```

Fixed it. Thanks :p

**Comment by dhruvbatra205** [comment]
Facing the same problem. Making those changes in the recovery.fstab doesn't help.
Could someone please guide me?

**Comment by volcano619** [comment]
Getting the same error,could someone help??
