### ISSUE TITLE
make workspace>>> Install framework resources for apktool... failed :(

### ISSUE THREAD

**Issue by uzushikakujin** [MiCode/patchrom#92]
can you help me in make workspace .. but im get this error

> > > Install framework resources for apktool...
> > > /home/uzu/patchrom/tools/apktool --quiet if /home/uzu/patchrom/miui/XHDPI/system/framework/framework-ext-res.apk
> > > Exception in thread "main" java.lang.UnsupportedClassVersionError: brut/apktool/Main : Unsupported major.minor version 51.0
> > >     at java.lang.ClassLoader.defineClass1(Native Method)
> > >     at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
> > >     at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
> > >     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
> > >     at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
> > >     at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
> > >     at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
> > >     at java.security.AccessController.doPrivileged(Native Method)
> > >     at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
> > >     at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
> > >     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
> > >     at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
> > > Could not find the main class: brut.apktool.Main. Program will exit.
> > > /home/uzu/patchrom/build/util.mk:39: recipe for target 'out/apktool-if' failed
> > > make: **\* [out/apktool-if] Error 1

sorry for my bad english ..

**Comment by Jaskaranbir** [comment]
You seem to be using a newer jdk.
Try jdk 6.

Additional info:
KitKat works with jdk 6
Lollipop works with jdk 7
Patchrom is currently kitkat.

**Comment by uzushikakujin** [comment]
thank sir :+1:
